import jsPDF from 'jspdf'

// ─── Color palette ────────────────────────────────────────────────────────────
const C = {
  primary:   [19, 236, 55],
  dark:      [15, 20, 15],
  white:     [255, 255, 255],
  gray:      [110, 115, 110],
  lightGray: [245, 247, 245],
  midGray:   [200, 204, 200],
  soil:      [59, 130, 246],
  temp:      [249, 115, 22],
  humidity:  [20, 184, 166],
  ph:        [168, 85, 247],
  water:     [239, 68, 68],
}

const SENSOR_COLORS = {
  soil:       C.soil,
  temp:       C.temp,
  humidity:   C.humidity,
  ph:         C.ph,
  waterLevel: C.water,
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function fmtVal(value, sensorKey) {
  if (value == null || isNaN(value)) return '--'
  if (sensorKey === 'ph') return value.toFixed(1) + ' pH'
  if (sensorKey === 'temp') return value.toFixed(1) + '°C'
  return Math.round(value) + '%'
}

function fmtDate(date) {
  return date.toLocaleDateString('en', { day: 'numeric', month: 'long', year: 'numeric' })
}

function fmtTime(date) {
  return date.toLocaleTimeString('en', { hour: '2-digit', minute: '2-digit' })
}

// Draw the green header band used on every report
function drawHeader(pdf, W, title, subtitle, rightLine1, rightLine2) {
  pdf.setFillColor(...C.primary)
  pdf.rect(0, 0, W, 30, 'F')

  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(19)
  pdf.setTextColor(...C.dark)
  pdf.text('AGROEZURAN', 14, 13)

  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(9)
  pdf.text(title, 14, 22)

  if (subtitle) {
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(8)
    pdf.text(subtitle, 14 + pdf.getTextWidth('AGROEZURAN') + 4, 13)
  }

  if (rightLine1) {
    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(8)
    pdf.setTextColor(...C.dark)
    pdf.text(rightLine1, W - 14, 13, { align: 'right' })
  }
  if (rightLine2) {
    pdf.setFontSize(9)
    pdf.text(rightLine2, W - 14, 22, { align: 'right' })
  }
}

// Draw footer band
function drawFooter(pdf, W, H) {
  pdf.setFillColor(...C.primary)
  pdf.rect(0, H - 12, W, 12, 'F')
  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(8)
  pdf.setTextColor(...C.dark)
  pdf.text('Generated by AgroEzuran  ·  PutraHack 2026  ·  IoT Smart Farm System', W / 2, H - 4, { align: 'center' })
}

// Draw the inline line chart using jsPDF primitives
function drawLineChart(pdf, chartData, sensorKey, rangeKey, x, y, w, h) {
  // Background
  pdf.setFillColor(...C.lightGray)
  pdf.roundedRect(x, y, w, h, 2, 2, 'F')
  pdf.setDrawColor(...C.midGray)
  pdf.setLineWidth(0.15)
  pdf.roundedRect(x, y, w, h, 2, 2, 'S')

  if (!chartData || chartData.length < 2) {
    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(8)
    pdf.setTextColor(...C.gray)
    pdf.text('No chart data available for this period', x + w / 2, y + h / 2, { align: 'center' })
    return
  }

  const pad = { l: 12, r: 4, t: 4, b: 8 }
  const cx = x + pad.l
  const cy = y + pad.t
  const cw = w - pad.l - pad.r
  const ch = h - pad.t - pad.b

  const values = chartData.map(d => d.value)
  const minVal = Math.min(...values)
  const maxVal = Math.max(...values)
  const range = maxVal - minVal || 1

  // Gridlines + Y-axis labels (4 lines)
  for (let i = 1; i <= 3; i++) {
    const gy = cy + (ch / 4) * i
    pdf.setDrawColor(220, 224, 220)
    pdf.setLineWidth(0.15)
    pdf.line(cx, gy, cx + cw, gy)

    const val = maxVal - (range / 4) * i
    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(5.5)
    pdf.setTextColor(...C.gray)
    const label = sensorKey === 'ph' ? val.toFixed(1) : Math.round(val) + ''
    pdf.text(label, cx - 1, gy + 1.5, { align: 'right' })
  }

  // Downsample: max 80 points
  const sampled = chartData.length > 80
    ? chartData.filter((_, i) => i % Math.ceil(chartData.length / 80) === 0)
    : chartData

  // Map to canvas coords
  const pts = sampled.map((d, i) => ({
    px: cx + (i / (sampled.length - 1)) * cw,
    py: cy + ch - ((d.value - minVal) / range) * ch,
  }))

  // Draw line segments
  const [r, g, b] = SENSOR_COLORS[sensorKey] ?? C.primary
  pdf.setDrawColor(r, g, b)
  pdf.setLineWidth(0.9)
  for (let i = 0; i < pts.length - 1; i++) {
    pdf.line(pts[i].px, pts[i].py, pts[i + 1].px, pts[i + 1].py)
  }

  // End dot
  pdf.setFillColor(r, g, b)
  pdf.circle(pts[pts.length - 1].px, pts[pts.length - 1].py, 1.3, 'F')
  pdf.setFillColor(...C.lightGray)
  pdf.circle(pts[pts.length - 1].px, pts[pts.length - 1].py, 0.6, 'F')

  // X-axis labels (4 evenly spaced)
  const labelIs = [0, Math.floor(sampled.length / 3), Math.floor((2 * sampled.length) / 3), sampled.length - 1]
  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(6)
  pdf.setTextColor(...C.gray)
  labelIs.forEach(i => {
    if (!pts[i] || !sampled[i]) return
    const d = new Date(sampled[i].timestamp)
    const label = rangeKey === '30d'
      ? d.toLocaleDateString('en', { month: 'short', day: 'numeric' })
      : d.toLocaleDateString('en', { weekday: 'short' })
    pdf.text(label, pts[i].px, cy + ch + 6, { align: 'center' })
  })
}

// ─── Export: Single Farm PDF (Farmer + Admin) ─────────────────────────────────

export function exportFarmPDF({
  cropType,
  fieldName,
  deviceId,
  sensorKey,
  sensorLabel,
  rangeKey,
  stats,
  liveData,
  annotations,
  chartData,
  adminName,
}) {
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const W = 210
  const H = 297
  const now = new Date()
  let y = 0

  // ── Header ───────────────────────────────────────────────────
  drawHeader(pdf, W,
    'Farm Analytics Report',
    null,
    adminName ? `Prepared by: ${adminName}` : null,
    `${fmtDate(now)}  ${fmtTime(now)}`
  )
  y = 40

  // ── Farm details ─────────────────────────────────────────────
  pdf.setFillColor(...C.lightGray)
  pdf.roundedRect(14, y, W - 28, 40, 3, 3, 'F')

  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(7)
  pdf.setTextColor(...C.gray)
  pdf.text('FARM DETAILS', 20, y + 8)

  const leftDetails  = [['Crop Type', cropType ?? 'Unknown'], ['Field', fieldName ?? 'Field A'], ['Device ID', deviceId ?? '--']]
  const rightDetails = [['Sensor', sensorLabel], ['Period', `Last ${rangeKey === '7d' ? '7 Days' : '30 Days'}`], ['Report Date', fmtDate(now)]]

  pdf.setFontSize(9)
  leftDetails.forEach(([lbl, val], i) => {
    pdf.setFont('helvetica', 'bold');  pdf.setTextColor(50, 50, 50)
    pdf.text(lbl, 20, y + 17 + i * 7)
    pdf.setFont('helvetica', 'normal'); pdf.setTextColor(80, 80, 80)
    pdf.text(`: ${val}`, 52, y + 17 + i * 7)
  })
  rightDetails.forEach(([lbl, val], i) => {
    pdf.setFont('helvetica', 'bold');  pdf.setTextColor(50, 50, 50)
    pdf.text(lbl, 118, y + 17 + i * 7)
    pdf.setFont('helvetica', 'normal'); pdf.setTextColor(80, 80, 80)
    pdf.text(`: ${val}`, 138, y + 17 + i * 7)
  })
  y += 50

  // ── Stats cards ──────────────────────────────────────────────
  if (stats) {
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(7)
    pdf.setTextColor(...C.gray)
    pdf.text('SENSOR SUMMARY', 14, y)
    y += 5

    const cardW = (W - 28 - 8) / 3
    const cards = [
      { label: 'AVERAGE', value: fmtVal(stats.avg, sensorKey), color: C.primary },
      { label: 'MINIMUM', value: fmtVal(stats.min, sensorKey), color: C.soil },
      { label: 'MAXIMUM', value: fmtVal(stats.max, sensorKey), color: C.temp },
    ]
    cards.forEach((card, i) => {
      const cx = 14 + i * (cardW + 4)
      pdf.setFillColor(...card.color)
      pdf.roundedRect(cx, y, cardW, 22, 3, 3, 'F')
      pdf.setTextColor(...C.dark)
      pdf.setFont('helvetica', 'bold')
      pdf.setFontSize(7)
      pdf.text(card.label, cx + cardW / 2, y + 7, { align: 'center' })
      pdf.setFontSize(15)
      pdf.text(card.value, cx + cardW / 2, y + 17, { align: 'center' })
    })
    y += 30
  }

  // ── Trend chart ──────────────────────────────────────────────
  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(7)
  pdf.setTextColor(...C.gray)
  pdf.text('TREND CHART', 14, y)
  y += 4

  drawLineChart(pdf, chartData, sensorKey, rangeKey, 14, y, W - 28, 58)
  y += 66

  // ── Live sensor snapshot ─────────────────────────────────────
  if (liveData) {
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(7)
    pdf.setTextColor(...C.gray)
    pdf.text('LIVE SENSOR SNAPSHOT', 14, y)
    y += 5

    pdf.setFillColor(...C.lightGray)
    pdf.roundedRect(14, y, W - 28, 26, 3, 3, 'F')

    const readings = [
      { label: 'Soil Moisture',  value: `${liveData.soil ?? '--'}%`,                                              color: C.soil },
      { label: 'Temperature',    value: `${liveData.temp ?? '--'}°C`,                                             color: C.temp },
      { label: 'Humidity',       value: `${liveData.humidity ?? '--'}%`,                                          color: [20, 184, 166] },
      { label: 'pH Level',       value: `${typeof liveData.ph === 'number' ? liveData.ph.toFixed(1) : '--'} pH`,  color: [168, 85, 247] },
      { label: 'Water Level',    value: `${liveData.waterLevel ?? '--'}%`,                                        color: C.water },
    ]
    const cellW = (W - 28) / 5
    readings.forEach((r, i) => {
      const rx = 14 + i * cellW
      pdf.setFont('helvetica', 'bold')
      pdf.setFontSize(7)
      pdf.setTextColor(...r.color)
      pdf.text(r.label, rx + cellW / 2, y + 9, { align: 'center' })
      pdf.setFontSize(11)
      pdf.setTextColor(30, 30, 30)
      pdf.text(r.value, rx + cellW / 2, y + 20, { align: 'center' })

      // Vertical separator
      if (i < 4) {
        pdf.setDrawColor(...C.midGray)
        pdf.setLineWidth(0.2)
        pdf.line(rx + cellW, y + 4, rx + cellW, y + 22)
      }
    })
    y += 34
  }

  // ── Admin notes ──────────────────────────────────────────────
  if (annotations?.length) {
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(7)
    pdf.setTextColor(...C.gray)
    pdf.text('ADMIN NOTES', 14, y)
    y += 5

    annotations.forEach(note => {
      if (y > H - 30) { pdf.addPage(); y = 20 }

      pdf.setFillColor(230, 255, 235)
      pdf.roundedRect(14, y, W - 28, 18, 2, 2, 'F')
      pdf.setFillColor(...C.primary)
      pdf.roundedRect(14, y, 3, 18, 1, 1, 'F')

      pdf.setFont('helvetica', 'bold')
      pdf.setFontSize(8)
      pdf.setTextColor(...C.primary)
      pdf.text(note.admin_name ?? 'Admin', 20, y + 7)

      if (note.sensor_type && note.sensor_type !== 'general') {
        const lx = 20 + pdf.getTextWidth(note.admin_name ?? 'Admin') + 3
        pdf.setFontSize(7)
        pdf.setTextColor(...C.gray)
        pdf.text(`[${note.sensor_type}]`, lx, y + 7)
      }

      pdf.setFont('helvetica', 'normal')
      pdf.setFontSize(8)
      pdf.setTextColor(40, 40, 40)
      const lines = pdf.splitTextToSize(note.message ?? '', W - 38)
      pdf.text(lines[0], 20, y + 14)
      y += 22
    })
  }

  // ── Footer ───────────────────────────────────────────────────
  drawFooter(pdf, W, H)

  const filename = `AgroEzuran_${(cropType ?? 'Farm').replace(/\s+/g, '_')}_${sensorLabel.replace(/\s+/g, '_')}_${rangeKey}.pdf`
  pdf.save(filename)
}

// ─── Export: All Farms Summary PDF (Admin only) ───────────────────────────────

export function exportAllFarmsPDF({ allCrops, liveSnapshots, adminName }) {
  const pdf = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })
  const W = 297
  const H = 210
  const now = new Date()
  let y = 0

  // ── Header ───────────────────────────────────────────────────
  drawHeader(pdf, W,
    'All Farms Summary Report',
    null,
    adminName ? `Admin: ${adminName}` : null,
    `${fmtDate(now)}  ${fmtTime(now)}`
  )
  y = 38

  // ── Subtitle ─────────────────────────────────────────────────
  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(8)
  pdf.setTextColor(...C.gray)
  pdf.text(`Total active farms: ${allCrops.length}   ·   Snapshot of live sensor readings at time of export`, 14, y)
  y += 8

  // ── Table ────────────────────────────────────────────────────
  const cols = [
    { label: '#',         x: 14,  w: 8   },
    { label: 'CROP',      x: 22,  w: 30  },
    { label: 'FIELD',     x: 52,  w: 35  },
    { label: 'DEVICE',    x: 87,  w: 50  },
    { label: 'SOIL',      x: 137, w: 25  },
    { label: 'TEMP',      x: 162, w: 25  },
    { label: 'HUMIDITY',  x: 187, w: 28  },
    { label: 'pH',        x: 215, w: 22  },
    { label: 'WATER',     x: 237, w: 26  },
    { label: 'STATUS',    x: 263, w: 28  },
  ]

  // Header row
  pdf.setFillColor(25, 30, 25)
  pdf.rect(14, y, W - 28, 9, 'F')
  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(7)
  pdf.setTextColor(...C.primary)
  cols.forEach(col => pdf.text(col.label, col.x + 2, y + 6))
  y += 9

  // Data rows
  allCrops.forEach((crop, idx) => {
    if (y > H - 18) { pdf.addPage(); y = 20 }

    const isEven = idx % 2 === 0
    pdf.setFillColor(isEven ? 248 : 243, isEven ? 250 : 246, isEven ? 248 : 243)
    pdf.rect(14, y, W - 28, 9, 'F')

    const snap = liveSnapshots?.[crop.device_id] ?? {}
    const isOnline = snap.lastSeen ? (Date.now() / 1000 - snap.lastSeen) < 300 : false

    const rowVals = [
      { col: cols[0], val: String(idx + 1),                                                         color: C.gray   },
      { col: cols[1], val: (crop.crop_type ?? '--').slice(0, 14),                                    color: null     },
      { col: cols[2], val: (crop.field_name ?? 'Field A').slice(0, 16),                              color: null     },
      { col: cols[3], val: (crop.device_id ?? '--').slice(0, 20),                                    color: C.gray   },
      { col: cols[4], val: snap.soil != null ? `${Math.round(snap.soil)}%` : '--',                   color: C.soil   },
      { col: cols[5], val: snap.temp != null ? `${Math.round(snap.temp)}°C` : '--',                  color: C.temp   },
      { col: cols[6], val: snap.humidity != null ? `${Math.round(snap.humidity)}%` : '--',           color: [20, 184, 166] },
      { col: cols[7], val: snap.ph != null ? `${Number(snap.ph).toFixed(1)} pH` : '--',              color: [168, 85, 247] },
      { col: cols[8], val: snap.waterLevel != null ? `${Math.round(snap.waterLevel)}%` : '--',       color: C.water  },
      { col: cols[9], val: isOnline ? 'Online' : 'Offline',                                         color: isOnline ? C.primary : C.gray },
    ]

    rowVals.forEach(({ col, val, color }) => {
      pdf.setFont('helvetica', color ? 'bold' : 'normal')
      pdf.setFontSize(8)
      pdf.setTextColor(...(color ?? [35, 35, 35]))
      pdf.text(val, col.x + 2, y + 6)
    })

    // Row divider
    pdf.setDrawColor(...C.midGray)
    pdf.setLineWidth(0.1)
    pdf.line(14, y + 9, W - 14, y + 9)
    y += 9
  })

  // ── Footer ───────────────────────────────────────────────────
  drawFooter(pdf, W, H)

  pdf.save(`AgroEzuran_All_Farms_Summary_${now.toISOString().slice(0, 10)}.pdf`)
}
